<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php';
require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
